databases:
  - name: testplatform-db
    databaseName: testplatform
    user: testplatform_user

services:
  - type: web
    name: testplatform-service
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: testplatform-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: testplatform-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: testplatform-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: testplatform-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: testplatform-db
          property: password
      - key: DB_SSL_OPTION
        value: ?sslmode=require
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
